// This file is auto-generated by the migration script
// Contains 301 redirects from old WordPress URLs to new URLs

export interface Redirect {
  source: string
  destination: string
  permanent: boolean
}

export const redirects: Redirect[] = [
  // Will be populated by migration script
  // Example:
  // {
  //   source: '/products/صفحه-کلید-هوشمند-استاندارد',
  //   destination: '/products/smart-keypad-standard',
  //   permanent: true,
  // },
]

export default redirects
